import Background from './background';
import CharacterClass from './character_class';
import CharacterStat from './character_stat';
import DeathSave from './death_save';
import Dice from './dice';
import Alignment from './enums/alignment';
import Equipment from './equipment';
import HitPoint from './hit_point';
import Language from './language';
import Race from './race';
import SavingThrow from './saving_throw';
import Skill from './skill';
import Talent from './talent';

export default class Character {
    id: number;
    name: string;
    class: CharacterClass;
    level: number;
    background: Background;
    player_name: string;
    race: Race;
    alignment: Alignment;
    experience_points: number;
    inspiration: number;
    proficiency_bonus: number;
    armor_class: number;
    initiative: number;
    speed: number;
    hit_point: HitPoint;
    hit_dice: Dice;
    death_saves: DeathSave;
    personality_traits: string;
    ideals: string;
    bonds: string;
    flaws: string;
    talents: Talent[];
    equipments: Equipment[];
    languages: Language[];
    stats: CharacterStat[];
    saving_throws: SavingThrow[];
    skills: Skill[];
    passive_perception: number;
    proficiencies: Equipment[];
}
